language: php

php:
  - 7.2
  - 7.4

matrix:
  fast_finish: true

  include:
    - php: 7.4
      env: PHPCS=1

    - php: 7.2
      env: PREFER_LOWEST=1

install:
  - if [[ $PREFER_LOWEST != 1 ]]; then composer install --prefer-dist --no-interaction ; fi
  - if [[ $PREFER_LOWEST == 1 ]]; then composer update --prefer-dist --no-interaction --prefer-lowest --prefer-stable ; fi

script:
  - sh -c "if [ '$PHPCS' != '1' ]; then vendor/bin/phpunit; fi"
  - sh -c "if [ '$PHPCS' = '1' ]; then ./vendor/bin/phpcs -n -p --extensions=php --standard=vendor/cakephp/cakephp-codesniffer/CakePHP src/ tests/; fi"

cache:
  directories:
    - $HOME/.composer/cache

notifications:
  email: false
